// <auto-generated>
// Rewired Constants
// This list was generated on 3/2/2023 9:50:43 PM
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace RewiredConsts {
    public static partial class Action {
        // Default
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Horizontal")]
        public const int Horizontal = 0;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Jump")]
        public const int Jump = 1;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Vertical")]
        public const int Vertical = 2;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Special")]
        public const int Special = 3;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Punch")]
        public const int Punch = 4;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Kick")]
        public const int Kick = 5;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Projectile")]
        public const int Projectile = 6;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Parry")]
        public const int Parry = 7;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Interact")]
        public const int Interact = 8;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Start")]
        public const int Start = 9;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Inventory")]
        public const int Inventory = 10;
        // UI
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Reserved UI actions", friendlyName = "UICancel")]
        public const int UICancel = 12;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Reserved UI actions", friendlyName = "MouseMovement")]
        public const int MouseMovement = 14;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Reserved UI actions", friendlyName = "UIHorizontal")]
        public const int UIHorizontal = 15;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Reserved UI actions", friendlyName = "UIVertical")]
        public const int UIVertical = 16;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Reserved UI actions", friendlyName = "UISubmit")]
        public const int UISubmit = 17;
    }
    public static partial class Category {
        public const int Default = 0;
        public const int UI = 5;
    }
    public static partial class Layout {
        public static partial class Joystick {
            public const int Default = 0;
        }
        public static partial class Keyboard {
            public const int Default = 0;
        }
        public static partial class Mouse {
            public const int Default = 0;
        }
        public static partial class CustomController {
            public const int Default = 0;
        }
    }
    public static partial class Player {
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "System")]
        public const int System = 9999999;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player0")]
        public const int Player0 = 0;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player1")]
        public const int Player1 = 1;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player2")]
        public const int Player2 = 2;
    }
    public static partial class CustomController {
        public static partial class FalseInput {
            public const int sourceId = 1;
            public const string name = "FalseInput";
            public static readonly System.Guid typeGuid = new System.Guid("4d0ffc02-5604-448d-b92f-bb3ba1844251");
            public static partial class Axis {
                public const int AI_Horizontal = 0;
                public const int AI_Vertical = 6;
            }
            public static partial class Button {
                public const int AI_Jump = 1;
                public const int AI_Punch = 2;
                public const int AI_Kick = 3;
                public const int AI_Projectile = 4;
                public const int AI_Special = 5;
                public const int AI_Parry = 7;
            }
        }
    }
    public static partial class LayoutManagerRuleSet {
    }
    public static partial class MapEnablerRuleSet {
    }
}
